##
# ** Copyright (C) 2026 Advanced Micro Devices, Inc. All rights reserved.
# ** Licensed under the MIT License.
##

add_executable(hip-mlir-opt hip-mlir-opt.cpp)

add_dependencies(hip-mlir-opt
  HipDialectIncGen
  HipsrDialectIncGen
  OnnxDialectIncGen
  HipsrConversionPassIncGen
  HipsrTransformsPassIncGen
  HipTypesIncGen
  HipOpsIncGen
  HipPassesIncGen
)
if(TARGET HipPdllPatterns)
  add_dependencies(hip-mlir-opt HipPdllPatterns)
endif()

target_link_libraries(hip-mlir-opt PRIVATE
  HipSupport
  LibHipCompiler
  HipDialectIR
  HipsrDialectIR
  OnnxDialectIR
  HipsrDialectTransforms
  HipsrDialectPipelines
  HipsrSchemePass
  HipDialectTransforms
  HipToLLVM
  OnnxToHip
  OnnxToHipsr
  MLIROptLib
  MLIRSupport
  MLIRIR
  MLIRParser
  MLIRPass
  MLIRTransforms
  MLIRAnalysis
  MLIRAffineDialect
  MLIRArithDialect
  MLIRControlFlowDialect
  MLIRFuncDialect
  MLIRMemRefDialect
  MLIRMemRefTransforms
  MLIRSCFDialect
  MLIRShapeDialect
  MLIRTensorDialect
  MLIRTensorInferTypeOpInterfaceImpl
  MLIRDestinationStyleOpInterface
  MLIRBufferizationDialect
  MLIRBufferizationTransforms
  MLIRBufferizationPipelines
  MLIRBufferizationToMemRef
  MLIRArithTransforms
  MLIRSCFTransforms
  MLIRTensorTransforms
  MLIRFuncTransforms
  MLIRLLVMDialect
  MLIRLLVMCommonConversion
  MLIRArithToLLVM
  MLIRMemRefToLLVM
  MLIRFuncToLLVM
  MLIRIndexToLLVM
  MLIRSCFToControlFlow
  MLIRControlFlowToLLVM
  MLIRConvertToLLVMPass
  MLIRReconcileUnrealizedCasts
  MLIRTransformUtils
  ${llvm_libs}
)

# Install target
install(TARGETS hip-mlir-opt
  RUNTIME DESTINATION bin
)
